---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gonosqltests-deployment
  labels:
    app: gonosqltests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gonosqltestsi
  template:
    metadata:
      labels:
        app: gonosqltests
    spec:
      containers:
      - name: gonosqltests
        image: bonifacekabaso/gonosqltests:0.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gonosqltests-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30030
  selector:
    app: gonosqltests